/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edgar.reto5.view;

import com.edgar.reto5.model.vo.InfoLiderVo;
import com.edgar.reto5.controller.ReportesController;
import com.edgar.reto5.model.vo.ComprasPorProyectoVo;
import com.edgar.reto5.model.vo.ProyectosPorClasificacionVo;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beelz
 */
public class ReportesView extends javax.swing.JFrame {

    int xMouse, yMouse;
    private static final ReportesController controller;

    static {
        controller = new ReportesController();
    }

    public ReportesView() {
        initComponents();
        TablaInforme1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaAlerta = new javax.swing.JOptionPane();
        Contenedor = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        tituloInforme = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Informe3_btn = new javax.swing.JButton();
        Informe1_btn = new javax.swing.JButton();
        Informe2_btn = new javax.swing.JButton();
        PanelImg = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        segundoApellido = new javax.swing.JLabel();
        segundoNombre = new javax.swing.JLabel();
        primerNombre = new javax.swing.JLabel();
        primerApellido = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        DescripcionInforme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(800, 600));
        Contenedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ContenedorMouseDragged(evt);
            }
        });
        Contenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContenedorMousePressed(evt);
            }
        });
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(74, 1, 254));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloInforme.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 24)); // NOI18N
        tituloInforme.setForeground(new java.awt.Color(238, 254, 0));
        tituloInforme.setText("INFORMES");
        PanelMenu.add(tituloInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        foto.setIcon(new javax.swing.ImageIcon("/media/beelz/MisionTIC2022/CICLO 2/Programación Básica/RETOS/RETO 5/Reto5/src/main/java/com/edgar/reto5/images/fotoE.png")); // NOI18N
        PanelMenu.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(238, 254, 0));
        jSeparator1.setForeground(new java.awt.Color(238, 254, 0));
        PanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 10));

        jSeparator2.setBackground(new java.awt.Color(238, 254, 0));
        jSeparator2.setForeground(new java.awt.Color(238, 254, 0));
        PanelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 10));

        Informe3_btn.setBackground(new java.awt.Color(238, 254, 0));
        Informe3_btn.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 16)); // NOI18N
        Informe3_btn.setForeground(new java.awt.Color(233, 50, 100));
        Informe3_btn.setText("TERCER INFORME");
        Informe3_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Informe3_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Informe3_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Informe3_btnMouseExited(evt);
            }
        });
        Informe3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informe3_btnActionPerformed(evt);
            }
        });
        PanelMenu.add(Informe3_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 180, -1));

        Informe1_btn.setBackground(new java.awt.Color(238, 254, 0));
        Informe1_btn.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 16)); // NOI18N
        Informe1_btn.setForeground(new java.awt.Color(233, 50, 100));
        Informe1_btn.setText("PRIMER INFORME");
        Informe1_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Informe1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Informe1_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Informe1_btnMouseExited(evt);
            }
        });
        Informe1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informe1_btnActionPerformed(evt);
            }
        });
        PanelMenu.add(Informe1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, -1));

        Informe2_btn.setBackground(new java.awt.Color(238, 254, 0));
        Informe2_btn.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 16)); // NOI18N
        Informe2_btn.setForeground(new java.awt.Color(233, 50, 100));
        Informe2_btn.setText("SEGUNDO INFORME");
        Informe2_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Informe2_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Informe2_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Informe2_btnMouseExited(evt);
            }
        });
        Informe2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informe2_btnActionPerformed(evt);
            }
        });
        PanelMenu.add(Informe2_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, -1));

        Contenedor.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 470));

        PanelImg.setBackground(new java.awt.Color(238, 254, 0));
        PanelImg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon("/media/beelz/MisionTIC2022/CICLO 2/Programación Básica/RETOS/RETO 5/Reto5/src/main/java/com/edgar/reto5/images/logo.png")); // NOI18N
        PanelImg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 130));
        Logo.getAccessibleContext().setAccessibleDescription("");

        segundoApellido.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 24)); // NOI18N
        segundoApellido.setForeground(new java.awt.Color(59, 99, 172));
        segundoApellido.setText("GONZALEZ");
        PanelImg.add(segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        segundoNombre.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 24)); // NOI18N
        segundoNombre.setForeground(new java.awt.Color(233, 50, 100));
        segundoNombre.setText("DAVID");
        PanelImg.add(segundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        primerNombre.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 24)); // NOI18N
        primerNombre.setForeground(new java.awt.Color(59, 99, 172));
        primerNombre.setText("EDGAR");
        PanelImg.add(primerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        primerApellido.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 24)); // NOI18N
        primerApellido.setForeground(new java.awt.Color(233, 50, 100));
        primerApellido.setText("LOZADA");
        PanelImg.add(primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        close_btn.setBackground(new java.awt.Color(238, 254, 0));
        close_btn.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 15)); // NOI18N
        close_btn.setForeground(java.awt.Color.red);
        close_btn.setText("X");
        close_btn.setBorderPainted(false);
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        PanelImg.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, 30));

        Contenedor.add(PanelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 130));

        Tabla.setAutoCreateRowSorter(true);
        Tabla.setFont(new java.awt.Font("Roboto Mono Light for Powerline", 0, 15)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(Tabla);

        Contenedor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 480, 330));

        DescripcionInforme.setFont(new java.awt.Font("Roboto Mono Medium for Powerline", 0, 18)); // NOI18N
        DescripcionInforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescripcionInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contenedor.add(DescripcionInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 480, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Informe3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informe3_btnActionPerformed
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        DescripcionInforme.setText("INFORME DE COMPRAS");
        try {
            var compras = controller.findComprasPorProyecto();
            if (!compras.isEmpty()) {
                modelo.addColumn("ID COMPRA");
                modelo.addColumn("CONSTRUCTORA");
                modelo.addColumn("BANCO VINCULADO");

                for (ComprasPorProyectoVo compra : compras) {
                    modelo.addRow(new Object[]{compra.getID_Compra(), compra.getConstructura(), compra.getBanco_Vinculado()});
                }
                Tabla.setModel(modelo);
                int[] anchos = {80, 200, 175};
                for (int i = 0; i < Tabla.getColumnCount(); i++) {
                    Tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
                Tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            } else {
                System.out.println("\nNo hay compras");
                ventanaAlerta.showMessageDialog(null,
                        "No hay compras para mostrar",
                        "Alerta",
                        ventanaAlerta.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            System.err.println("Ha ocurrido un error: " + e.getMessage());
            ventanaAlerta.showMessageDialog(null,
                    e.getMessage(),
                    "Error en el infrome 3",
                    ventanaAlerta.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Informe3_btnActionPerformed

    private void Informe1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informe1_btnActionPerformed
        TablaInforme1();
    }//GEN-LAST:event_Informe1_btnActionPerformed

    private void Informe2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informe2_btnActionPerformed
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        DescripcionInforme.setText("INFORME DE PROYECTOS");
        try {
            var proyectos = controller.findProyectosPorClasificacionVo();
            if (!proyectos.isEmpty()) {
                modelo.addColumn("ID");
                modelo.addColumn("CONSTRUCTORA");
                modelo.addColumn("NUMERO HABITACIONES");
                modelo.addColumn("CIUDAD");

                for (ProyectosPorClasificacionVo proyecto : proyectos) {
                    modelo.addRow(new Object[]{proyecto.getID_Proyecto(), proyecto.getConstructora(), proyecto.getNumero_Habitaciones(), proyecto.getCiudad()});
                }
                Tabla.setModel(modelo);
                int[] anchos = {40, 200, 160, 120};
                for (int i = 0; i < Tabla.getColumnCount(); i++) {
                    Tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
                Tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            } else {
                System.out.println("\nNo hay proyectos");
                ventanaAlerta.showMessageDialog(null,
                        "No hay proyectos para mostrar",
                        "Alerta",
                        ventanaAlerta.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            System.err.println("Ha ocurrido un error: " + e.getMessage());
            ventanaAlerta.showMessageDialog(null,
                    e.getMessage(),
                    "Error en el infrome 2",
                    ventanaAlerta.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Informe2_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        if (ventanaAlerta.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", ventanaAlerta.YES_NO_OPTION) == ventanaAlerta.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void ContenedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_ContenedorMousePressed

    private void ContenedorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_ContenedorMouseDragged

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        close_btn.setBackground(primerNombre.getForeground());
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        close_btn.setBackground(PanelImg.getBackground());

    }//GEN-LAST:event_close_btnMouseExited

    private void Informe1_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe1_btnMouseEntered
        Informe1_btn.setForeground(tituloInforme.getForeground());
        Informe1_btn.setBackground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe1_btnMouseEntered

    private void Informe1_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe1_btnMouseExited
        Informe1_btn.setBackground(tituloInforme.getForeground());
        Informe1_btn.setForeground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe1_btnMouseExited

    private void Informe2_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe2_btnMouseEntered
        Informe2_btn.setForeground(tituloInforme.getForeground());
        Informe2_btn.setBackground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe2_btnMouseEntered

    private void Informe2_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe2_btnMouseExited
        Informe2_btn.setBackground(tituloInforme.getForeground());
        Informe2_btn.setForeground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe2_btnMouseExited

    private void Informe3_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe3_btnMouseEntered
        Informe3_btn.setForeground(tituloInforme.getForeground());
        Informe3_btn.setBackground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe3_btnMouseEntered

    private void Informe3_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Informe3_btnMouseExited
        Informe3_btn.setBackground(tituloInforme.getForeground());
        Informe3_btn.setForeground(segundoNombre.getForeground());
    }//GEN-LAST:event_Informe3_btnMouseExited

    private void TablaInforme1() {
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        DescripcionInforme.setText("INFORME DE LIDERES");
        try {
            var lideres = controller.findInfoLider();
            if (!lideres.isEmpty()) {

                modelo.addColumn("ID");
                modelo.addColumn("NOMBRE");
                modelo.addColumn("PRIMER APELLIDO");
                modelo.addColumn("CIUDAD DE RESIDENCIA");

                for (InfoLiderVo lider : lideres) {
                    modelo.addRow(new Object[]{lider.getID_Lider(), lider.getNombre(), lider.getPrimer_Apellido(), lider.getCiudad_Residencia()});
                }
                Tabla.setModel(modelo);
                int[] anchos = {60, 100, 120, 170};
                for (int i = 0; i < Tabla.getColumnCount(); i++) {
                    Tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }
                Tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            } else {
                System.out.println("\nNo hay lideres");
                ventanaAlerta.showMessageDialog(null,
                        "No hay lideres para mostrar",
                        "Alerta",
                        ventanaAlerta.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            System.err.println("Ha ocurrido un error: " + e.getMessage());
            ventanaAlerta.showMessageDialog(null,
                    e.getMessage(),
                    "Error en el infrome 1",
                    ventanaAlerta.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void run(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel DescripcionInforme;
    private javax.swing.JButton Informe1_btn;
    private javax.swing.JButton Informe2_btn;
    private javax.swing.JButton Informe3_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelImg;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel foto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel primerApellido;
    private javax.swing.JLabel primerNombre;
    private javax.swing.JLabel segundoApellido;
    private javax.swing.JLabel segundoNombre;
    private javax.swing.JLabel tituloInforme;
    private javax.swing.JOptionPane ventanaAlerta;
    // End of variables declaration//GEN-END:variables
}
